### ISSUE TITLE
Refactor ha_storage variable

### ISSUE THREAD

**Issue by mgrzybek** [mgrzybek/ansible-ha-storage#2]
For instance, you can only deploy one volume group per play. So as to deploy several volume groups, a list of properties should be given, such as:

```yaml
# Global parameters
ha_storage_global:
    use_sfex_ra_github: true
    http_proxy: http://proxy.local

# Volume groups
ha_storage_volume_groups:
    # First volume group
    - volume_group: test
      fs: zfs
      zpool_mountpoint: /srv
      use_clvm: false
      use_sfex: true
      cluster_attribute_name: role
      cluster_attribute_value: cache
      luns:
          - id: /dev/disk/by-id/ata-VBOX_HARDDISK_VB60e589c7-a5211949
            alias: lun-dc-1
      filesystems:
          - lv: log
            size: 2G
            fstype: xfs
            mountpoint: /srv/log
          - lv: cache
            size: 2G
            fstype: xfs
            mountpoint: /srv/squid

    # Another volume group
    - volume_group: db
      fs: zfs
      zpool_mountpoint: /srv
      cluster_attribute_name: role
      cluster_attribute_value: database
      luns:
        - id: /dev/vdb
          alias: lun-dc-1
        - id: /dev/vdc
          alias: lun-dc-2
      filesystems:
        - lv: data
          size: 20GB
          mountpoint: data
        - lv: xlog
          size: 2GB
          mountpoint: xlog
```
