### ISSUE TITLE
[crm script] create resources instead of appending existeng ones

### ISSUE THREAD

**Issue by mgrzybek** [mgrzybek/ansible-ha-storage#3]
In order to append resources to tho storage group we need to run cluster commands to create them.
It could be easier to let the role create them for us. For example, they could be directly written in the `crm script`.

Before:
```
  vars:
    ha_storage:
      openrc: /etc/openrc.sh
      cinder_volumes:
        - 55659db9-1bea-46e1-a894-4b257be72bdd
        - 548ef897-32b6-4331-99b7-4823ac6680cd
      volume_group: db
      filesystems:
        - lv: data
          size: 20G
          fstype: xfs
          mountpoint: /srv/data
      append_resources:
        - name: pgsql
```

After:
```
  vars:
    ha_storage:
      openrc: /etc/openrc.sh
      cinder_volumes:
        - 55659db9-1bea-46e1-a894-4b257be72bdd
        - 548ef897-32b6-4331-99b7-4823ac6680cd
      volume_group: db
      filesystems:
        - lv: data
          size: 20G
          fstype: xfs
          mountpoint: /srv/data
      append_resources:
        -  name: postgresql-service
           type: docker
           params:
               - allow_pull=true
               - image=postgresql:11
               - run_opts="-v /srv/data:/data"
```
